############### DEVELOPMENT IMAGE ###############

FROM node:14.7.0-alpine3.10 as dev

RUN mkdir /work/
WORKDIR /work/

COPY ./src/package.json /work/package.json
RUN npm install
RUN npm install -g nodemon

COPY ./src/ /work/src/

############### PRODUCTION IMAGE ###############

FROM dev as prod

CMD node .
