version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DBNAME=cars
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13.1-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
