version: '3'
services:
    app:
        container_name: fake-dev
        build:
            context: .
            target: dev
        volumes:
            - .:/app
        ports:
            - 5001:5000
            - 5678:5678
