version: '3'
services:
    app:
        container_name: fake-prod
        build:
            context: .
            target: prod
        volumes:
            - .:/app
        ports:
            - 8080:80
