version: "3"
services:
  fake-service:
    build:
      context: .
    container_name: fake-service
    ports:
      - "8080:5000"
    volumes:
      - ./src:/app
  prometheus:
    container_name: prometheus-service
    image: prom/prometheus
    ports: 
      - "9091:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
