version: "3.4"
services:
    # Note:
    # This is the same as 'docker run -it -v ${pwd}:/work -w /work -p 5000:5000 {image} /bin/sh'
    # when running 'docker-compose build fxncy'.
    fxncy:
        container_name: fxncy
        build: 
            context: ./fxncy
            target: dev
        # working_dir: /work
        # entrypoint: /bin/sh
        # stdin_open: true
        # tty: true
        volumes:
            - ./fxncy/src/:/work/src
        ports:
            - 5000:5000
            - 9229:9229
    # jelly:
    #     container_name: jelly
    #     # image:
    #     build:
    #         context: ./jelly
    #         target: dev
    #     working_dir: /work
    #     entrypoint: /bin/sh
    #     stdin_open: true
    #     tty: true
    #     volumes
    #         - ./jelly/src/:/work
    #     ports
    #         - 5001:5000
    piepie:
        container_name: piepie
        build:
            context: ./piepie
            target: dev
        # working_dir: /work 
        # entrypoint: /bin/sh
        # stdin_open: true
        # tty: true
        volumes:
            - ./piepie/src/:/work
        ports:
            - 5002:5000        # Port for flask application
            - 5678:5678        # Extra port for debugger process
    