version: 3
services:
    # Note:
    # This is the same as 'docker run -it -v ${pwd}:/work -w /work -p 5000:5000 {image} /bin/sh'
    # when running 'docker-compose build fxncy'.
    fxncy:
        container_name: fxncy
        # image:
        build: 
            context: ./fxncy
            target: dev
        working_dir: /work     # Comment out for build.target:prod
        entry_point: /bin/sh   # Comment out for build.target:prod
        stdin_open: true       # Comment out for build.target:prod
        tty: true              # Comment out for build.target:prod
        volumes:
            - ./fxncy/src/:/work
        ports:
            - 5000:5000
    jelly:
        container_name: jelly
        # image:
        build:
            context: ./jelly
            target: dev
        working_dir: /work     # Comment out for build.target:prod
        entry_point: /bin/sh   # Comment out for build.target:prod
        stdin_open: true       # Comment out for build.target:prod
        tty: true              # Comment out for build.target:prod
        volumes:
            - ./fxncy/src/:/work
        ports:
            - 5001:5000
    piepie:
        container_name: piepie
        # image:
        build:
            context: ./piepie
            target: dev
        working_dir: /work     # Comment out for build.target:prod
        entry_point: /bin/sh   # Comment out for build.target:prod
        stdin_open: true       # Comment out for build.target:prod
        tty: true              # Comment out for build.target:prod
        volumes:
            - ./fxncy/src/:/work
        ports:
            - 5002:5000        # Port for flask application
            - 5678:5678        # Extra port for debugger process
    