FROM openjdk:11-jdk-buster as dev

WORKDIR /work

COPY mvnw /work/mvnw
COPY .mvn /work/.mvn
COPY pom.xml /work/pom.xml

COPY . /work

RUN ./mvnw clean install
RUN chmod +x /work/target/jelly-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/work/target/jelly-0.0.1-SNAPSHOT.jar"]
