# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_booking.proto',
  package='bookie',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63\x61r_booking.proto\x12\x06\x62ookie\"7\n\x13\x43\x61rInventoryRequest\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\r\x12\x10\n\x08quantity\x18\x02 \x01(\r\"T\n\x11\x43\x61rInventoryReply\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\r\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x11\n\tavailable\x18\x04 \x01(\r\"G\n\x0e\x43\x61rBookRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x04\x12\x0e\n\x06\x63\x61r_id\x18\x02 \x01(\x04\x12\x10\n\x08quantity\x18\x03 \x01(\r\"O\n\x0c\x43\x61rBookReply\x12\x0e\n\x06\x63\x61r_id\x18\x01 \x01(\r\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x11\n\tpurchased\x18\x04 \x01(\r2\x90\x01\n\tCarBooker\x12H\n\x0c\x41\x64\x64Inventory\x12\x1b.bookie.CarInventoryRequest\x1a\x19.bookie.CarInventoryReply\"\x00\x12\x39\n\x07\x42ookCar\x12\x16.bookie.CarBookRequest\x1a\x14.bookie.CarBookReply\"\x00\x62\x06proto3'
)




_CARINVENTORYREQUEST = _descriptor.Descriptor(
  name='CarInventoryRequest',
  full_name='bookie.CarInventoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_id', full_name='bookie.CarInventoryRequest.car_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='bookie.CarInventoryRequest.quantity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=84,
)


_CARINVENTORYREPLY = _descriptor.Descriptor(
  name='CarInventoryReply',
  full_name='bookie.CarInventoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_id', full_name='bookie.CarInventoryReply.car_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand', full_name='bookie.CarInventoryReply.brand', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='bookie.CarInventoryReply.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available', full_name='bookie.CarInventoryReply.available', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=170,
)


_CARBOOKREQUEST = _descriptor.Descriptor(
  name='CarBookRequest',
  full_name='bookie.CarBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='bookie.CarBookRequest.customer_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='car_id', full_name='bookie.CarBookRequest.car_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='bookie.CarBookRequest.quantity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=243,
)


_CARBOOKREPLY = _descriptor.Descriptor(
  name='CarBookReply',
  full_name='bookie.CarBookReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_id', full_name='bookie.CarBookReply.car_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand', full_name='bookie.CarBookReply.brand', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='bookie.CarBookReply.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='purchased', full_name='bookie.CarBookReply.purchased', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['CarInventoryRequest'] = _CARINVENTORYREQUEST
DESCRIPTOR.message_types_by_name['CarInventoryReply'] = _CARINVENTORYREPLY
DESCRIPTOR.message_types_by_name['CarBookRequest'] = _CARBOOKREQUEST
DESCRIPTOR.message_types_by_name['CarBookReply'] = _CARBOOKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarInventoryRequest = _reflection.GeneratedProtocolMessageType('CarInventoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARINVENTORYREQUEST,
  '__module__' : 'car_booking_pb2'
  # @@protoc_insertion_point(class_scope:bookie.CarInventoryRequest)
  })
_sym_db.RegisterMessage(CarInventoryRequest)

CarInventoryReply = _reflection.GeneratedProtocolMessageType('CarInventoryReply', (_message.Message,), {
  'DESCRIPTOR' : _CARINVENTORYREPLY,
  '__module__' : 'car_booking_pb2'
  # @@protoc_insertion_point(class_scope:bookie.CarInventoryReply)
  })
_sym_db.RegisterMessage(CarInventoryReply)

CarBookRequest = _reflection.GeneratedProtocolMessageType('CarBookRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARBOOKREQUEST,
  '__module__' : 'car_booking_pb2'
  # @@protoc_insertion_point(class_scope:bookie.CarBookRequest)
  })
_sym_db.RegisterMessage(CarBookRequest)

CarBookReply = _reflection.GeneratedProtocolMessageType('CarBookReply', (_message.Message,), {
  'DESCRIPTOR' : _CARBOOKREPLY,
  '__module__' : 'car_booking_pb2'
  # @@protoc_insertion_point(class_scope:bookie.CarBookReply)
  })
_sym_db.RegisterMessage(CarBookReply)



_CARBOOKER = _descriptor.ServiceDescriptor(
  name='CarBooker',
  full_name='bookie.CarBooker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddInventory',
    full_name='bookie.CarBooker.AddInventory',
    index=0,
    containing_service=None,
    input_type=_CARINVENTORYREQUEST,
    output_type=_CARINVENTORYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BookCar',
    full_name='bookie.CarBooker.BookCar',
    index=1,
    containing_service=None,
    input_type=_CARBOOKREQUEST,
    output_type=_CARBOOKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARBOOKER)

DESCRIPTOR.services_by_name['CarBooker'] = _CARBOOKER

# @@protoc_insertion_point(module_scope)
