# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import car_booking_pb2 as car__booking__pb2


class CarBookerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddInventory = channel.unary_unary(
                '/bookie.CarBooker/AddInventory',
                request_serializer=car__booking__pb2.CarInventoryRequest.SerializeToString,
                response_deserializer=car__booking__pb2.CarInventoryReply.FromString,
                )
        self.BookCar = channel.unary_unary(
                '/bookie.CarBooker/BookCar',
                request_serializer=car__booking__pb2.CarBookRequest.SerializeToString,
                response_deserializer=car__booking__pb2.CarBookReply.FromString,
                )


class CarBookerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddInventory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BookCar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarBookerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddInventory': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInventory,
                    request_deserializer=car__booking__pb2.CarInventoryRequest.FromString,
                    response_serializer=car__booking__pb2.CarInventoryReply.SerializeToString,
            ),
            'BookCar': grpc.unary_unary_rpc_method_handler(
                    servicer.BookCar,
                    request_deserializer=car__booking__pb2.CarBookRequest.FromString,
                    response_serializer=car__booking__pb2.CarBookReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bookie.CarBooker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarBooker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddInventory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookie.CarBooker/AddInventory',
            car__booking__pb2.CarInventoryRequest.SerializeToString,
            car__booking__pb2.CarInventoryReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BookCar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bookie.CarBooker/BookCar',
            car__booking__pb2.CarBookRequest.SerializeToString,
            car__booking__pb2.CarBookReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
